# Javascript Node CircleCI 2.0 configuration file
# Reference https://circleci.com/docs/2.1/language-javascript/
version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:12.16

references:
  save_package_cache: &save_package_cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - ./node_modules

  restore_package_cache: &restore_package_cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}

commands:
  npm-publish:
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

jobs:
  test:
    executor: nodejs
    steps:
      - checkout
      - restore_cache: *restore_package_cache
      - run: yarn install --frozen-lockfile
      - save_cache: *save_package_cache
      - run: yarn format:check
      - run: yarn lint
      - run: yarn test:ci

  release:
    executor: nodejs
    steps:
      - checkout
      - restore_cache: *restore_package_cache
      - run: yarn install --frozen-lockfile
      - save_cache: *save_package_cache
      - run: yarn build
      - npm-publish

workflows:
  version: 2
  test-build-and-release:
    jobs:
      - test
      - release:
          context: IGG
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
